[package]
name = "brtdp"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
num-traits = "0.2"
ordered-float = { version = "2.8.0", features = ["serde"] }
rand = "0.7.0"
mdp = { path = "../mdp" }
