use crate::common::coordinate2::Coordinate2;

use super::{mdp::SalomeGridMDP, state::SalomeGridState};

impl SalomeGridMDP {
    pub fn example() -> SalomeGridMDP {
        let obstacles = vec![
            SalomeGridState::new(0, 0),
            SalomeGridState::new(0, 1),
            SalomeGridState::new(0, 2),
            SalomeGridState::new(0, 3),
            SalomeGridState::new(0, 4),
            SalomeGridState::new(0, 5),
            SalomeGridState::new(0, 6),
            SalomeGridState::new(0, 7),
            SalomeGridState::new(0, 8),
            SalomeGridState::new(0, 9),
            SalomeGridState::new(0, 10),
            SalomeGridState::new(1, 0),
            SalomeGridState::new(2, 0),
            SalomeGridState::new(3, 0),
            SalomeGridState::new(4, 0),
            SalomeGridState::new(5, 0),
            SalomeGridState::new(6, 0),
            SalomeGridState::new(7, 0),
            SalomeGridState::new(8, 0),
            SalomeGridState::new(9, 0),
            SalomeGridState::new(1, 10),
            SalomeGridState::new(2, 10),
            SalomeGridState::new(3, 10),
            SalomeGridState::new(4, 10),
            SalomeGridState::new(5, 10),
            SalomeGridState::new(6, 10),
            SalomeGridState::new(7, 10),
            SalomeGridState::new(8, 10),
            SalomeGridState::new(9, 10),
            SalomeGridState::new(9, 0),
            SalomeGridState::new(9, 1),
            SalomeGridState::new(9, 2),
            SalomeGridState::new(9, 3),
            SalomeGridState::new(9, 4),
            SalomeGridState::new(9, 5),
            SalomeGridState::new(9, 6),
            SalomeGridState::new(9, 7),
            SalomeGridState::new(9, 8),
            SalomeGridState::new(9, 9),
            SalomeGridState::new(9, 10),
            SalomeGridState::new(2, 2),
            SalomeGridState::new(2, 3),
            SalomeGridState::new(2, 4),
            SalomeGridState::new(2, 5),
            SalomeGridState::new(2, 6),
            SalomeGridState::new(2, 7),
            SalomeGridState::new(2, 8),
            SalomeGridState::new(3, 2),
            SalomeGridState::new(3, 3),
            SalomeGridState::new(3, 4),
            SalomeGridState::new(4, 2),
            SalomeGridState::new(4, 3),
            SalomeGridState::new(4, 4),
            SalomeGridState::new(5, 2),
            SalomeGridState::new(5, 3),
            SalomeGridState::new(5, 4),
            SalomeGridState::new(6, 2),
            SalomeGridState::new(6, 3),
            SalomeGridState::new(6, 4),
            SalomeGridState::new(7, 2),
            SalomeGridState::new(7, 3),
            SalomeGridState::new(7, 4),
        ];
        let mdp = SalomeGridMDP::new(10, 11, obstacles, Coordinate2 { i: 1, j: 9 })
            .set_initial_state(SalomeGridState::new(8, 1));
        mdp
    }
}
